services:
    david63.friendsandfoes.admin.controller:
        class: david63\friendsandfoes\controller\admin_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@pagination'
            - '@language'
            - '@david63.friendsandfoes.core.functions'
            - '%tables%'

    david63.friendsandfoes.core.functions:
        class: david63\friendsandfoes\core\functions
        arguments:
            - '@ext.manager'

    _defaults:
        public: true
